anti fx added!
AndrewR3K/bcc-anticheat pull request #5
Opened 2023-09-20 20:34 UTC by Zaps6000

2023-09-26 22:49 UTC, AndrewR3K requested changes
Was this feature tested fully within RedM?

2023-09-26 22:49 UTC, AndrewR3K commented on config.lua
> +Config.FX = { -- OHHHH YEAAA
Please remove comment, it has no use.

2023-09-26 22:49 UTC, AndrewR3K commented on config.lua
> +    limit = 600, -- Default Value (2088 = Golden Core Health)
Please remove the copy/pasted comment.

2023-09-26 22:49 UTC, AndrewR3K commented on config.lua
> +    "FX_EVENT_NAME_2",
Are these real events? if not lets comment them out as examples.

2023-09-26 22:49 UTC, AndrewR3K commented on config.lua
> +    }
This is a copy/paste. This field should be used when the player is being kicked so that servers with other languages can set it how they want.

2023-09-26 22:49 UTC, AndrewR3K commented on server/server.lua
> +            local message = string.format('[BCC Anticheat]: Player %s caused event %s too many times with data %s', sender, eventName, eventDataString)
This should utilize the lang.kickreason in the fx config.

2023-10-05 23:30 UTC, Zaps6000 commented
works was tested

2023-10-06 00:15 UTC, merged